[linux] remove unused get_primary_display() (#161)
This fixes the following build error:
```
window_manager_plugin.cc:527:26: error: unused function 'get_primary_display' [-Werror,-Wunused-function]
```